damareen/urls.py
"""
Damareen URL Configuration
"""
from django.urls import path
from . import views

app_name = 'damareen'

urlpatterns = [
    # Főoldal
    path('', views.index, name='index'),
    
    # Játékmester nézetek
    path('master/', views.master_dashboard, name='master_dashboard'),
    path('master/kornyezet/create/', views.create_kornyezet, name='create_kornyezet'),
    path('master/kornyezet/<int:kornyezet_id>/', views.view_kornyezet, name='view_kornyezet'),
    
    # Világkártyák kezelése
    path('master/vilagkartyak/', views.manage_vilagkartyak, name='manage_vilagkartyak'),
    path('master/vilagkartyak/create/', views.create_vilagkartya, name='create_vilagkartya'),
    path('master/vilagkartyak/<int:kartya_id>/edit/', views.edit_vilagkartya, name='edit_vilagkartya'),
    path('master/vilagkartyak/<int:kartya_id>/delete/', views.delete_vilagkartya, name='delete_vilagkartya'),
    
    # Vezérkártyák kezelése
    path('master/vezerkartyak/', views.manage_vezerkartyak, name='manage_vezerkartyak'),
    path('master/vezerkartyak/create/', views.create_vezerkartya, name='create_vezerkartya'),
    path('master/vezerkartyak/<int:kartya_id>/delete/', views.delete_vezerkartya, name='delete_vezerkartya'),
    
    # Kazamaták kezelése
    path('master/kazamatak/', views.manage_kazamatak, name='manage_kazamatak'),
    path('master/kazamatak/create/', views.create_kazamata, name='create_kazamata'),
    path('master/kazamatak/<int:kazamata_id>/edit/', views.edit_kazamata, name='edit_kazamata'),
    path('master/kazamatak/<int:kazamata_id>/delete/', views.delete_kazamata, name='delete_kazamata'),
    
    # Játékos nézetek
    path('player/', views.player_dashboard, name='player_dashboard'),
    path('player/jatek/start/<int:kornyezet_id>/', views.start_game, name='start_game'),
    path('player/jatek/<int:jatek_id>/', views.game_view, name='game_view'),
    path('player/jatek/<int:jatek_id>/pakli/', views.pakli_osszeallit, name='pakli_osszeallit'),
    path('player/jatek/<int:jatek_id>/harc/<int:kazamata_id>/', views.harc_indit, name='harc_indit'),
    path('player/game/<int:jatek_id>/battle/<int:kazamata_id>/', views.battle_arena, name='battle_arena'),
    path('player/jatek/<int:jatek_id>/harc/<int:harc_id>/eredmeny/', views.harc_eredmeny, name='harc_eredmeny'),
    path('player/game/<int:jatek_id>/harc/<int:harc_id>/jutalom/', views.jutalom_valaszt, name='jutalom_valaszt'),
    
    # Autentikáció
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    
    # Rangsor és achievementek
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('achievements/', views.my_achievements, name='achievements'),
]

dusza25/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('damareen.urls')),
]

damareen/forms.py
from django import forms
from .models import Kazamata, Vilagkartya, Vezerkartya


class KazamataForm(forms.ModelForm):
    """Form a kazamata létrehozásához és szerkesztéséhez"""
    
    class Meta:
        model = Kazamata
        fields = ['nev', 'tipus']
        widgets = {
            'nev': forms.TextInput(attrs={
                'class': 'input-field',
                'placeholder': 'pl. A sötét kripta',
                'maxlength': 100
            }),
            'tipus': forms.Select(attrs={
                'class': 'input-field'
            }),
        }
        labels = {
            'nev': 'Kazamata neve',
            'tipus': 'Kazamata típusa'
        }


class VilagkartyaForm(forms.ModelForm):
    """Form a világkártya létrehozásához és szerkesztéséhez"""
    
    class Meta:
        model = Vilagkartya
        fields = ['nev', 'tipus', 'sebzes', 'eletero']
        widgets = {
            'nev': forms.TextInput(attrs={
                'class': 'input-field',
                'placeholder': 'pl. Tűz varázsló',
                'maxlength': 16
            }),
            'tipus': forms.Select(attrs={
                'class': 'input-field'
            }),
            'sebzes': forms.NumberInput(attrs={
                'class': 'input-field',
                'min': 2,
                'max': 100,
                'placeholder': '2-100'
            }),
            'eletero': forms.NumberInput(attrs={
                'class': 'input-field',
                'min': 1,
                'max': 100,
                'placeholder': '1-100'
            }),
        }
        labels = {
            'nev': 'Kártya neve',
            'tipus': 'Elem típusa',
            'sebzes': 'Sebzés',
            'eletero': 'Életerő'
        }


class VezerkartyaForm(forms.ModelForm):
    """Form a vezérkártya létrehozásához"""
    
    class Meta:
        model = Vezerkartya
        fields = ['eredeti_kartya', 'duplazas_tipusa']
        widgets = {
            'eredeti_kartya': forms.Select(attrs={
                'class': 'input-field',
                'onchange': 'updatePreview()'
            }),
            'duplazas_tipusa': forms.RadioSelect()
        }
        labels = {
            'eredeti_kartya': 'Alap kártya',
            'duplazas_tipusa': 'Mit duplázunk?'
        }

damareen/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.db import transaction
from django.db.models import Max

from .models import (
    UserProfile, JatekKornyezet, Jatek, Jatekoskartya,
    Pakli, PakliKartya, Kazamata, Harc, Vilagkartya,
    Vezerkartya, GyujtemenyKartya, KazamataKartya,
    Achievement, PlayerAchievement,
    ELEMENT_FIRE, ELEMENT_EARTH, ELEMENT_WATER, ELEMENT_AIR
)
from .game_logic import harc_vegrehajtasa, jutalom_alkalmazasa, frissit_rangsort
from .forms import KazamataForm, VilagkartyaForm, VezerkartyaForm


def index(request):
    """Főoldal"""
    return render(request, 'damareen/index.html')


def user_login(request):
    """Bejelentkezés"""
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            messages.success(request, f'Üdvözöl a Damareen, {user.username}!')
            return redirect('damareen:index')
        else:
            messages.error(request, 'Hibás felhasználónév vagy jelszó!')
    
    return render(request, 'damareen/login.html')


def user_logout(request):
    """Kijelentkezés"""
    logout(request)
    messages.info(request, 'Sikeresen kijelentkeztél!')
    return redirect('damareen:index')


def user_register(request):
    """Regisztráció"""
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')
        user_type = request.POST.get('user_type', UserProfile.PERMISSION_PLAYER)
        
        if password != password2:
            messages.error(request, 'A jelszavak nem egyeznek!')
        elif User.objects.filter(username=username).exists():
            messages.error(request, 'Ez a felhasználónév már foglalt!')
        else:
            user = User.objects.create_user(username=username, password=password)
            UserProfile.objects.create(user=user, user_type=user_type)
            messages.success(request, 'Sikeres regisztráció! Most már bejelentkezhetsz.')
            return redirect('damareen:login')
    
    return render(request, 'damareen/register.html')


@login_required
def master_dashboard(request):
    """Játékmester műszerfal"""
    kornyezetek = JatekKornyezet.objects.filter(keszitette=request.user)
    vilag_kartyak = Vilagkartya.objects.all()
    vezer_kartyak = Vezerkartya.objects.all()
    kazamatak = Kazamata.objects.all()
    
    return render(request, 'damareen/master/dashboard.html', {
        'kornyezetek': kornyezetek,
        'vilag_kartyak': vilag_kartyak,
        'vezer_kartyak': vezer_kartyak,
        'kazamatak': kazamatak,
    })


@login_required
def create_kornyezet(request):
    """Új játékkörnyezet létrehozása"""
    if request.method == 'POST':
        nev = request.POST.get('nev')
        
        # Játékkörnyezet létrehozása
        kornyezet = JatekKornyezet.objects.create(
            nev=nev,
            keszitette=request.user
        )
        
        messages.success(request, f'Játékkörnyezet "{nev}" létrehozva!')
        return redirect('damareen:view_kornyezet', kornyezet_id=kornyezet.id)
    
    vilag_kartyak = Vilagkartya.objects.all()
    return render(request, 'damareen/master/create_kornyezet.html', {
        'vilag_kartyak': vilag_kartyak
    })


@login_required
def view_kornyezet(request, kornyezet_id):
    """Játékkörnyezet megtekintése"""
    kornyezet = get_object_or_404(JatekKornyezet, id=kornyezet_id, keszitette=request.user)
    
    if request.method == 'POST':
        # Kezdő gyűjtemény frissítése
        valasztott_kartyak = request.POST.getlist('kartyak')
        GyujtemenyKartya.objects.filter(kornyezet=kornyezet).delete()
        
        for kartya_id in valasztott_kartyak:
            GyujtemenyKartya.objects.create(
                kornyezet=kornyezet,
                kartya_id=kartya_id
            )
        
        messages.success(request, 'Kezdő gyűjtemény frissítve!')
    
    vilag_kartyak = Vilagkartya.objects.all()
    kezdo_gyujtemeny = kornyezet.kezdo_gyujtemeny.all()
    kazamatak = Kazamata.objects.all()
    
    return render(request, 'damareen/master/view_kornyezet.html', {
        'kornyezet': kornyezet,
        'vilag_kartyak': vilag_kartyak,
        'kezdo_gyujtemeny': kezdo_gyujtemeny,
        'kazamatak': kazamatak
    })


@login_required
def player_dashboard(request):
    """Játékos műszerfal"""
    jatekok = Jatek.objects.filter(jatekos=request.user)
    kornyezetek = JatekKornyezet.objects.all()
    
    return render(request, 'damareen/player/dashboard.html', {
        'jatekok': jatekok,
        'kornyezetek': kornyezetek
    })


@login_required
@transaction.atomic
def start_game(request, kornyezet_id):
    """Új játék indítása"""
    kornyezet = get_object_or_404(JatekKornyezet, id=kornyezet_id)
    
    # Ellenőrizzük, hogy van-e már játék ezzel a környezettel
    jatek, created = Jatek.objects.get_or_create(
        jatekos=request.user,
        kornyezet=kornyezet
    )
    
    if created:
        # Kezdő gyűjtemény másolása
        for gyujtemeny_kartya in kornyezet.kezdo_gyujtemeny.all():
            Jatekoskartya.objects.create(
                jatek=jatek,
                eredeti_kartya=gyujtemeny_kartya.kartya,
                aktualis_sebzes=gyujtemeny_kartya.kartya.sebzes,
                aktualis_eletero=gyujtemeny_kartya.kartya.eletero
            )
        messages.success(request, f'Új játék indítva: {kornyezet.nev}')
    else:
        messages.info(request, 'Folytatod a megkezdett játékot.')
    
    return redirect('damareen:game_view', jatek_id=jatek.id)


@login_required
def game_view(request, jatek_id):
    """Játék nézet"""
    jatek = get_object_or_404(Jatek, id=jatek_id, jatekos=request.user)
    gyujtemeny = jatek.gyujtemeny.all()
    pakli = None
    
    try:
        pakli = jatek.pakli
    except Pakli.DoesNotExist:
        pass
    
    kazamatak = Kazamata.objects.all()
    utolso_harcok = jatek.harcok.filter(befejezve=True).order_by('-inditas')[:5]
    
    return render(request, 'damareen/player/game_view.html', {
        'jatek': jatek,
        'gyujtemeny': gyujtemeny,
        'pakli': pakli,
        'kazamatak': kazamatak,
        'utolso_harcok': utolso_harcok
    })


@login_required
@transaction.atomic
def pakli_osszeallit(request, jatek_id):
    """Pakli összeállítása"""
    jatek = get_object_or_404(Jatek, id=jatek_id, jatekos=request.user)
    
    if request.method == 'POST':
        valasztott_kartyak = request.POST.getlist('kartyak')
        
        if not valasztott_kartyak:
            messages.error(request, 'Válassz ki legalább egy kártyát!')
            return redirect('damareen:pakli_osszeallit', jatek_id=jatek_id)
        
        # Régi pakli törlése
        try:
            jatek.pakli.delete()
        except Pakli.DoesNotExist:
            pass
        
        # Új pakli létrehozása
        pakli = Pakli.objects.create(jatek=jatek)
        
        for i, kartya_id in enumerate(valasztott_kartyak):
            PakliKartya.objects.create(
                pakli=pakli,
                kartya_id=kartya_id,
                sorrend=i + 1
            )
        
        messages.success(request, f'Pakli összeállítva {len(valasztott_kartyak)} kártyával!')
        return redirect('damareen:game_view', jatek_id=jatek_id)
    
    gyujtemeny = jatek.gyujtemeny.all()
    return render(request, 'damareen/player/pakli_osszeallit.html', {
        'jatek': jatek,
        'gyujtemeny': gyujtemeny
    })


@login_required
@transaction.atomic
def harc_indit(request, jatek_id, kazamata_id):
    """Harc indítása - új: WebSocket alapú real-time battle"""
    jatek = get_object_or_404(Jatek, id=jatek_id, jatekos=request.user)
    kazamata = get_object_or_404(Kazamata, id=kazamata_id)
    
    # Ellenőrizzük, hogy van-e pakli
    try:
        pakli = jatek.pakli
    except Pakli.DoesNotExist:
        messages.error(request, '❌ Először állíts össze egy paklit!')
        return redirect('damareen:game_view', jatek_id=jatek_id)
    
    # Ellenőrizzük a kártyák számát
    pakli_meret = pakli.get_kartyak_szama()
    kazamata_meret = kazamata.get_kartyak_szama()
    
    if pakli_meret != kazamata_meret:
        messages.error(request, 
            f'❌ A paklidban {pakli_meret} kártya van, de a kazamatához {kazamata_meret} kell!')
        return redirect('damareen:game_view', jatek_id=jatek_id)
    
    # Redirect to WebSocket battle arena
    return redirect('damareen:battle_arena', jatek_id=jatek_id, kazamata_id=kazamata_id)


@login_required
def battle_arena(request, jatek_id, kazamata_id):
    """Real-time battle arena with WebSocket"""
    jatek = get_object_or_404(Jatek, id=jatek_id, jatekos=request.user)
    kazamata = get_object_or_404(Kazamata, id=kazamata_id)
    
    return render(request, 'damareen/player/battle_arena.html', {
        'jatek': jatek,
        'kazamata': kazamata
    })


@login_required
def harc_eredmeny(request, jatek_id, harc_id):
    """Harc eredményének megtekintése"""
    jatek = get_object_or_404(Jatek, id=jatek_id, jatekos=request.user)
    harc = get_object_or_404(Harc, id=harc_id, jatek=jatek)
    
    # Rangsor frissítése (csak egyszer)
    if harc.befejezve and not harc.rangsor_frissitve:
        frissit_rangsort(request.user, harc.jatekos_gyozott)

damareen/templates/damareen/player/dashboard.html
{% extends 'damareen/base.html' %}

{% block title %}Játékos műszerfal - Damareen{% endblock %}

{% block content %}
<h2>🎮 Játékos műszerfal</h2>

<div class="card">
    <h3>Folyamatban lévő játékok</h3>
    
    {% if jatekok %}
        <table>
            <thead>
                <tr>
                    <th>Játékkörnyezet</th>
                    <th>Indítás</th>
                    <th>Utolsó aktivitás</th>
                    <th>Műveletek</th>
                </tr>
            </thead>
            <tbody>
                {% for jatek in jatekok %}
                <tr>
                    <td><strong>{{ jatek.kornyezet.nev }}</strong></td>
                    <td>{{ jatek.inditas|date:"Y.m.d H:i" }}</td>
                    <td>{{ jatek.utolso_aktivitas|date:"Y.m.d H:i" }}</td>
                    <td>
                        <a href="{% url 'damareen:game_view' jatek.id %}" class="btn">
                            Folytatás
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p style="padding: 20px; text-align: center; color: #666;">
            Még nincs folyamatban lévő játékod. Indíts egyet az alábbi környezetek közül!
        </p>
    {% endif %}
</div>

<div class="card" style="margin-top: 30px;">
    <h3>Elérhető játékkörnyezetek</h3>
    
    {% if kornyezetek %}
        <div class="grid">
            {% for kornyezet in kornyezetek %}
            <div class="card" style="border: 2px solid #667eea;">
                <h4>{{ kornyezet.nev }}</h4>
                <p><small>Készítette: {{ kornyezet.keszitette.username }}</small></p>
                <p><small>Létrehozva: {{ kornyezet.letrehozva|date:"Y.m.d" }}</small></p>
                
                <div style="margin-top: 15px;">
                    <a href="{% url 'damareen:start_game' kornyezet.id %}" class="btn btn-success">
                        🎮 Játék indítása
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <p style="padding: 20px; text-align: center; color: #666;">
            Még nincs elérhető játékkörnyezet. Kérj meg egy játékmestert, hogy hozzon létre egyet!
        </p>
    {% endif %}
</div>
{% endblock %}

damareen/templates/damareen/player/harc_eredmeny.html
{% extends 'damareen/base.html' %}

{% block title %}Harc eredménye{% endblock %}

{% block extra_css %}
<style>
    .battle-result {
        text-align: center;
        padding: 30px;
        border-radius: 15px;
        margin: 30px 0;
        font-size: 28px;
        font-weight: bold;
        font-family: 'Cinzel', serif;
        text-transform: uppercase;
        letter-spacing: 3px;
    }
    
    .battle-result.victory {
        background: linear-gradient(135deg, rgba(46, 125, 50, 0.4) 0%, rgba(27, 94, 32, 0.4) 100%);
        border: 3px solid #4caf50;
        color: #90ee90;
        text-shadow: 0 0 20px rgba(76, 175, 80, 0.8);
        box-shadow: 0 0 30px rgba(76, 175, 80, 0.4);
    }
    
    .battle-result.defeat {
        background: linear-gradient(135deg, rgba(211, 47, 47, 0.4) 0%, rgba(183, 28, 28, 0.4) 100%);
        border: 3px solid #f44336;
        color: #ff6b6b;
        text-shadow: 0 0 20px rgba(244, 67, 54, 0.8);
        box-shadow: 0 0 30px rgba(244, 67, 54, 0.4);
    }
    
    .battle-grid {
        display: grid;
        grid-template-columns: 1fr auto 1fr;
        gap: 30px;
        align-items: start;
        margin: 30px 0;
        padding: 20px;
        background: rgba(20, 20, 40, 0.4);
        border-radius: 12px;
        border: 1px solid rgba(218, 165, 32, 0.2);
    }
    
    .battle-card {
        text-align: center;
        padding: 15px;
    }
    
    .battle-card.player {
        border-right: 2px solid rgba(52, 152, 219, 0.3);
    }
    
    .battle-card.enemy {
        border-left: 2px solid rgba(211, 47, 47, 0.3);
    }
    
    .battle-vs {
        text-align: center;
        font-size: 48px;
        color: #daa520;
        text-shadow: 0 0 20px rgba(218, 165, 32, 0.6);
        font-family: 'Cinzel', serif;
    }
    
    .battle-outcome {
        margin-top: 20px;
        padding: 15px;
        border-radius: 8px;
        font-size: 16px;
        text-align: center;
    }
    
    .battle-outcome.win {
        background: rgba(46, 125, 50, 0.3);
        border: 2px solid #4caf50;
        color: #90ee90;
    }
    
    .battle-outcome.lose {
        background: rgba(211, 47, 47, 0.3);
        border: 2px solid #f44336;
        color: #ff6b6b;
    }
    
    .round-number {
        display: inline-block;
        background: linear-gradient(135deg, #8b4513 0%, #654321 100%);
        color: #daa520;
        padding: 8px 20px;
        border-radius: 20px;
        font-family: 'Cinzel', serif;
        font-weight: 600;
        margin-bottom: 20px;
        border: 2px solid rgba(218, 165, 32, 0.5);
        box-shadow: 0 4px 8px rgba(0,0,0,0.3);
    }
    
    /* ============================================
       MOBILE RESPONSIVE STYLES
       ============================================ */
    
    /* Mobile devices (max-width: 768px) */
    @media screen and (max-width: 768px) {
        .battle-result {
            padding: 20px 15px;
            font-size: 22px;
            letter-spacing: 2px;
            margin: 20px 0;
        }
        
        .battle-grid {
            grid-template-columns: 1fr;
            grid-template-rows: auto auto auto;
            gap: 20px;
            padding: 15px;
            margin: 20px 0;
        }
        
        .battle-card.player {
            border-right: none;
            border-bottom: 2px solid rgba(52, 152, 219, 0.3);
            padding-bottom: 15px;
        }
        
        .battle-vs {
            font-size: 36px;
            order: 2;
            padding: 10px 0;
        }
        
        .battle-card.enemy {
            border-left: none;
            border-top: 2px solid rgba(211, 47, 47, 0.3);
            padding-top: 15px;
        }
        
        .battle-outcome {
            font-size: 14px;
            padding: 12px;
        }
        
        .round-number {
            padding: 6px 16px;
            font-size: 14px;
        }
        
        .kartya {
            margin: 10px auto !important;
            max-width: 100% !important;
        }
    }
    
    /* Small mobile devices (max-width: 480px) */
    @media screen and (max-width: 480px) {
        .battle-result {
            padding: 15px 10px;
            font-size: 18px;
            letter-spacing: 1px;
        }
        
        .battle-grid {
            gap: 15px;
            padding: 12px;
        }
        
        .battle-card h4 {
            font-size: 18px;
        }
        
        .battle-vs {
            font-size: 30px;
        }
        
        .battle-outcome {
            font-size: 13px;
            padding: 10px;
        }
        
        .round-number {
            padding: 5px 14px;
            font-size: 13px;
        }
    }
</style>
{% endblock %}

{% block content %}
<h2>⚔️ Harc eredménye</h2>

<div class="card">
    <h3>{{ harc.kazamata.nev }}</h3>
    <p><strong>{{ harc.kazamata.get_tipus_display }}</strong></p>
    <p>Időpont: {{ harc.inditas|date:"Y.m.d H:i" }}</p>
</div>

<div class="battle-result {% if harc.jatekos_gyozott %}victory{% else %}defeat{% endif %}">
    {% if harc.jatekos_gyozott %}
        🎉 GYŐZELEM! 🎉
    {% else %}
        😞 VERESÉG 😞
    {% endif %}
</div>

{% if harc.jatekos_gyozott %}
<div class="card" style="text-align: center; border-left-color: #4caf50;">
    <h3 style="color: #90ee90;">🏆 Jutalom</h3>
    <p style="font-size: 20px; color: #daa520;">{{ harc.kazamata.get_nyeremeny_leiras }}</p>
</div>
{% else %}
<div class="card" style="text-align: center; border-left-color: #f44336;">
    <p style="font-size: 18px; color: #ff6b6b;">
        Próbáld újra vagy állíts össze új paklit!
    </p>
</div>
{% endif %}

<div class="card" style="margin-top: 30px;">
    <h3>📊 Ütközetek részletei</h3>
    
    {% for utközet in utközetek %}
    <div style="margin: 30px 0;">
        <div style="text-align: center;">
            <span class="round-number">⚔️ Ütközet #{{ utközet.sorrend }}</span>
        </div>
        
        <div class="battle-grid">
            <!-- Játékos kártya -->
            <div class="battle-card player">
                <h4 style="color: #64b5f6; font-size: 22px;">👤 Saját kártya</h4>
                <div class="kartya kartya-{{ utközet.jatekos_tipus }}" style="margin: 15px auto; max-width: 250px;">
                    <h3>{{ utközet.jatekos_kartya.eredeti_kartya.nev }}</h3>
                    <div class="kartya-stat">
                        <span>⚔️ Sebzés:</span>
                        <span style="color: #daa520;">{{ utközet.jatekos_sebzes }}</span>
                    </div>
                    <div class="kartya-stat">
                        <span>❤️ Életerő:</span>
                        <span style="color: #e74c3c;">{{ utközet.jatekos_eletero }}</span>
                    </div>
                    <div style="margin-top: 10px; text-align: center;">
                        <span class="elem-icon elem-{{ utközet.jatekos_tipus }}">
                            {{ utközet.get_jatekos_tipus_display }}
                        </span>
                    </div>
                </div>
            </div>
            
            <!-- VS -->
            <div class="battle-vs">
                ⚔️
            </div>
            
            <!-- Kazamata kártya -->
            <div class="battle-card enemy">
                <h4 style="color: #ff6b6b; font-size: 22px;">🏰 Ellenség</h4>
                <div class="kartya kartya-{{ utközet.kazamata_tipus }}" style="margin: 15px auto; max-width: 250px;">
                    <h3>
                        {% if utközet.kazamata_kartya_ref.vilag_kartya %}
                            {{ utközet.kazamata_kartya_ref.vilag_kartya.nev }}
                        {% else %}
                            {{ utközet.kazamata_kartya_ref.vezer_kartya.nev }} 👑
                        {% endif %}
                    </h3>
                    <div class="kartya-stat">
                        <span>⚔️ Sebzés:</span>
                        <span style="color: #daa520;">{{ utközet.kazamata_sebzes }}</span>
                    </div>
                    <div class="kartya-stat">
                        <span>❤️ Életerő:</span>
                        <span style="color: #e74c3c;">{{ utközet.kazamata_eletero }}</span>
                    </div>
                    <div style="margin-top: 10px; text-align: center;">
                        <span class="elem-icon elem-{{ utközet.kazamata_tipus }}">
                            {{ utközet.get_kazamata_tipus_display }}
                        </span>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="battle-outcome {% if utközet.jatekos_nyert %}win{% else %}lose{% endif %}">
            <strong>
                {% if utközet.jatekos_nyert %}
                    ✅ Játékos győzött
                {% else %}
                    ❌ Kazamata győzött
                {% endif %}
            </strong>
            <br>
            <span style="font-size: 14px; opacity: 0.9;">{{ utközet.gyoztes_ok }}</span>
        </div>
    </div>
    {% endfor %}
</div>

<div style="margin-top: 40px; text-align: center;">
    {% if harc.jatekos_gyozott %}
        <a href="{% url 'damareen:jutalom_valaszt' jatek.id harc.id %}" class="btn btn-success" style="font-size: 18px;">
            🎁 Jutalom átvétele
        </a>
    {% else %}
        <a href="{% url 'damareen:game_view' jatek.id %}" class="btn" style="font-size: 18px;">
            🔙 Vissza a játékhoz
        </a>
    {% endif %}
</div>
{% endblock %}