damareen/urls.py
"""
Damareen URL Configuration
"""
from django.urls import path
from . import views

app_name = 'damareen'

urlpatterns = [
    # Főoldal
    path('', views.index, name='index'),
    
    # Játékmester nézetek
    path('master/', views.master_dashboard, name='master_dashboard'),
    path('master/kornyezet/create/', views.create_kornyezet, name='create_kornyezet'),
    path('master/kornyezet/<int:kornyezet_id>/', views.view_kornyezet, name='view_kornyezet'),
    
    # Világkártyák kezelése
    path('master/vilagkartyak/', views.manage_vilagkartyak, name='manage_vilagkartyak'),
    path('master/vilagkartyak/create/', views.create_vilagkartya, name='create_vilagkartya'),
    path('master/vilagkartyak/<int:kartya_id>/edit/', views.edit_vilagkartya, name='edit_vilagkartya'),
    path('master/vilagkartyak/<int:kartya_id>/delete/', views.delete_vilagkartya, name='delete_vilagkartya'),
    
    # Vezérkártyák kezelése
    path('master/vezerkartyak/', views.manage_vezerkartyak, name='manage_vezerkartyak'),
    path('master/vezerkartyak/create/', views.create_vezerkartya, name='create_vezerkartya'),
    path('master/vezerkartyak/<int:kartya_id>/delete/', views.delete_vezerkartya, name='delete_vezerkartya'),
    
    # Kazamaták kezelése
    path('master/kazamatak/', views.manage_kazamatak, name='manage_kazamatak'),
    path('master/kazamatak/create/', views.create_kazamata, name='create_kazamata'),
    path('master/kazamatak/<int:kazamata_id>/edit/', views.edit_kazamata, name='edit_kazamata'),
    path('master/kazamatak/<int:kazamata_id>/delete/', views.delete_kazamata, name='delete_kazamata'),
    
    # Játékos nézetek
    path('player/', views.player_dashboard, name='player_dashboard'),
    path('player/jatek/start/<int:kornyezet_id>/', views.start_game, name='start_game'),
    path('player/jatek/<int:jatek_id>/', views.game_view, name='game_view'),
    path('player/jatek/<int:jatek_id>/pakli/', views.pakli_osszeallit, name='pakli_osszeallit'),
    path('player/jatek/<int:jatek_id>/harc/<int:kazamata_id>/', views.harc_indit, name='harc_indit'),
    path('player/game/<int:jatek_id>/battle/<int:kazamata_id>/', views.battle_arena, name='battle_arena'),
    path('player/jatek/<int:jatek_id>/harc/<int:harc_id>/eredmeny/', views.harc_eredmeny, name='harc_eredmeny'),
    path('player/game/<int:jatek_id>/harc/<int:harc_id>/jutalom/', views.jutalom_valaszt, name='jutalom_valaszt'),
    
    # Autentikáció
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    
    # Rangsor és achievementek
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('achievements/', views.my_achievements, name='achievements'),
]

dusza25/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('damareen.urls')),
]

damareen/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

# Felhasználó profil
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    PERMISSION_PLAYER = 'player'
    PERMISSION_MASTER = 'master'

    PERMISSION_CHOICES = [
        (PERMISSION_PLAYER, 'Játékos'),
        (PERMISSION_MASTER, 'Játékmester'),
    ]

    user_type = models.CharField(max_length=10, choices=PERMISSION_CHOICES, default=PERMISSION_PLAYER)
    
    # Rangsor / Leaderboard mezők
    osszes_gyozelem = models.IntegerField(default=0, verbose_name="Összes győzelem")
    osszes_vereseg = models.IntegerField(default=0, verbose_name="Összes vereség")
    legmagasabb_sorozat = models.IntegerField(default=0, verbose_name="Leghosszabb győzelmi sorozat")
    jelenlegi_sorozat = models.IntegerField(default=0, verbose_name="Jelenlegi győzelmi sorozat")
    osszes_pontszam = models.IntegerField(default=0, verbose_name="Összes pontszám")

    def __str__(self):
        return f"{self.user.username} ({self.get_user_type_display()})"
    
    def gyozelem_hozzaad(self):
        """Győzelem hozzáadása és sorozat frissítése"""
        self.osszes_gyozelem += 1
        self.jelenlegi_sorozat += 1
        self.osszes_pontszam += 10
        
        if self.jelenlegi_sorozat > self.legmagasabb_sorozat:
            self.legmagasabb_sorozat = self.jelenlegi_sorozat
        
        self.save()
    
    def vereseg_hozzaad(self):
        """Vereség hozzáadása és sorozat nullázása"""
        self.osszes_vereseg += 1
        self.jelenlegi_sorozat = 0
        self.save()
    
    def get_gyozelem_arany(self):
        """Visszaadja a győzelmi arányt százalékban"""
        osszes_harc = self.osszes_gyozelem + self.osszes_vereseg
        if osszes_harc == 0:
            return 0
        return round((self.osszes_gyozelem / osszes_harc) * 100, 1)


# Achievement modell
class Achievement(models.Model):
    nev = models.CharField(max_length=100, unique=True, verbose_name="Név")
    leiras = models.TextField(verbose_name="Leírás")
    ikon = models.CharField(max_length=10, default='🏆', verbose_name="Ikon (emoji)")
    tipus = models.CharField(max_length=50, verbose_name="Típus")
    cel_ertek = models.IntegerField(verbose_name="Cél érték")
    pontok = models.IntegerField(default=10, verbose_name="Pontok")
    
    class Meta:
        verbose_name = "Achievement"
        verbose_name_plural = "Achievementek"
    
    def __str__(self):
        return f"{self.ikon} {self.nev}"


# Játékos achievementjei
class PlayerAchievement(models.Model):
    jatekos = models.ForeignKey(User, on_delete=models.CASCADE, related_name='achievementek')
    achievement = models.ForeignKey(Achievement, on_delete=models.CASCADE)
    megszerzve = models.DateTimeField(auto_now_add=True, verbose_name="Megszerzve")
    jelenlegi_haladás = models.IntegerField(default=0, verbose_name="Jelenlegi haladás")
    
    class Meta:
        verbose_name = "Játékos Achievement"
        verbose_name_plural = "Játékos Achievementek"
        unique_together = [['jatekos', 'achievement']]
    
    def __str__(self):
        return f"{self.jatekos.username} - {self.achievement.nev}"
    
    @property
    def teljesitve(self):
        """Igaz, ha az achievement teljesítve van"""
        return self.jelenlegi_haladás >= self.achievement.cel_ertek
    
    def get_haladás_szazalek(self):
        """Visszaadja a haladást százalékban"""
        if self.achievement.cel_ertek == 0:
            return 100
        return min(100, round((self.jelenlegi_haladás / self.achievement.cel_ertek) * 100, 1))


# Elem típusok konstansai
ELEMENT_FIRE = 'tuz'
ELEMENT_EARTH = 'fold'
ELEMENT_WATER = 'viz'
ELEMENT_AIR = 'levego'

ELEMENT_CHOICES = [
    (ELEMENT_FIRE, 'Tűz'),
    (ELEMENT_EARTH, 'Föld'),
    (ELEMENT_WATER, 'Víz'),
    (ELEMENT_AIR, 'Levegő'),
]


# Sima világkártya
class Vilagkartya(models.Model):
    nev = models.CharField(max_length=16, unique=True, verbose_name="Név")
    sebzes = models.IntegerField(
        validators=[MinValueValidator(2), MaxValueValidator(100)],
        verbose_name="Sebzés"
    )
    eletero = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(100)],
        verbose_name="Életerő"
    )
    tipus = models.CharField(max_length=10, choices=ELEMENT_CHOICES, verbose_name="Típus")
    
    class Meta:
        verbose_name = "Világkártya"
        verbose_name_plural = "Világkártyák"
    
    def __str__(self):
        return f"{self.nev} (S:{self.sebzes}, É:{self.eletero}, {self.get_tipus_display()})"


# Vezérkártya - származtatott a sima kártyából
class Vezerkartya(models.Model):
    DUPLICATION_DAMAGE = 'sebzes'
    DUPLICATION_HP = 'eletero'
    
    DUPLICATION_CHOICES = [
        (DUPLICATION_DAMAGE, 'Sebzés duplázás'),
        (DUPLICATION_HP, 'Életerő duplázás'),
    ]
    
    nev = models.CharField(max_length=16, unique=True, verbose_name="Név")
    eredeti_kartya = models.ForeignKey(Vilagkartya, on_delete=models.CASCADE, verbose_name="Eredeti kártya")
    duplazas_tipusa = models.CharField(max_length=10, choices=DUPLICATION_CHOICES, verbose_name="Duplázás típusa")
    
    class Meta:
        verbose_name = "Vezérkártya"
        verbose_name_plural = "Vezérkártyák"
    
    def __str__(self):
        return f"{self.nev} (Vezér - {self.eredeti_kartya.nev})"
    
    @property
    def sebzes(self):
        if self.duplazas_tipusa == self.DUPLICATION_DAMAGE:
            return self.eredeti_kartya.sebzes * 2
        return self.eredeti_kartya.sebzes
    
    @property
    def eletero(self):
        if self.duplazas_tipusa == self.DUPLICATION_HP:
            return self.eredeti_kartya.eletero * 2
        return self.eredeti_kartya.eletero
    
    @property
    def tipus(self):
        return self.eredeti_kartya.tipus
    
    def get_tipus_display(self):
        return self.eredeti_kartya.get_tipus_display()


# Kazamata
class Kazamata(models.Model):
    TIPUS_EGYSZERU = 'egyszeru'
    TIPUS_KIS = 'kis'
    TIPUS_NAGY = 'nagy'
    
    TIPUS_CHOICES = [
        (TIPUS_EGYSZERU, 'Egyszerű találkozás'),
        (TIPUS_KIS, 'Kis kazamata'),
        (TIPUS_NAGY, 'Nagy kazamata'),
    ]
    
    nev = models.CharField(max_length=100, unique=True, verbose_name="Név")
    tipus = models.CharField(max_length=10, choices=TIPUS_CHOICES, verbose_name="Típus")
    
    class Meta:
        verbose_name = "Kazamata"
        verbose_name_plural = "Kazamaták"
    
    def __str__(self):
        return f"{self.nev} ({self.get_tipus_display()})"
    
    def get_kartyak_szama(self):
        """Visszaadja, hogy hány kártyát tartalmaz a kazamata"""
        if self.tipus == self.TIPUS_EGYSZERU:
            return 1
        elif self.tipus == self.TIPUS_KIS:
            return 4  # 3 sima + 1 vezér
        elif self.tipus == self.TIPUS_NAGY:
            return 6  # 5 sima + 1 vezér
        return 0
    
    def get_nyeremeny_leiras(self):
        """Visszaadja a kazamata legyőzésének jutalmát"""
        if self.tipus == self.TIPUS_EGYSZERU:
            return "+1 sebzés"
        elif self.tipus == self.TIPUS_KIS:
            return "+2 életerő"
        elif self.tipus == self.TIPUS_NAGY:
            return "+3 sebzés"
        return ""


# Kazamata kártyák sorrendje
class KazamataKartya(models.Model):
    kazamata = models.ForeignKey(Kazamata, on_delete=models.CASCADE, related_name='kartyak')
    sorrend = models.IntegerField(verbose_name="Sorrend")
    
    # Lehet sima kártya vagy vezérkártya
    vilag_kartya = models.ForeignKey(Vilagkartya, on_delete=models.CASCADE, null=True, blank=True)
    vezer_kartya = models.ForeignKey(Vezerkartya, on_delete=models.CASCADE, null=True, blank=True)
    
    class Meta:
        verbose_name = "Kazamata kártya"
        verbose_name_plural = "Kazamata kártyák"
        ordering = ['sorrend']
        unique_together = [['kazamata', 'sorrend']]
    
    def __str__(self):
        kartya_nev = self.vilag_kartya.nev if self.vilag_kartya else self.vezer_kartya.nev
        return f"{self.kazamata.nev} - {self.sorrend}. {kartya_nev}"
    
    @property
    def kartya(self):
        """Visszaadja a kártyát (sima vagy vezér)"""
        return self.vilag_kartya if self.vilag_kartya else self.vezer_kartya
    
    @property
    def is_vezer(self):
        """Igaz, ha vezérkártya"""
        return self.vezer_kartya is not None
    
    def get_sebzes(self):
        if self.vilag_kartya:
            return self.vilag_kartya.sebzes
        return self.vezer_kartya.sebzes
    
    def get_eletero(self):
        if self.vilag_kartya:
            return self.vilag_kartya.eletero
        return self.vezer_kartya.eletero
    
    def get_tipus(self):
        if self.vilag_kartya:
            return self.vilag_kartya.tipus
        return self.vezer_kartya.tipus


# Játékkörnyezet
class JatekKornyezet(models.Model):
    nev = models.CharField(max_length=100, unique=True, verbose_name="Név")
    keszitette = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Készítette")
    letrehozva = models.DateTimeField(auto_now_add=True, verbose_name="Létrehozva")
    
    class Meta:
        verbose_name = "Játékkörnyezet"
        verbose_name_plural = "Játékkörnyezetek"
    
    def __str__(self):
        return self.nev


# Játékkörnyezet kezdő gyűjteménye
class GyujtemenyKartya(models.Model):
    kornyezet = models.ForeignKey(JatekKornyezet, on_delete=models.CASCADE, related_name='kezdo_gyujtemeny')
    kartya = models.ForeignKey(Vilagkartya, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = "Gyűjtemény kártya"

damareen/forms.py
from django import forms
from .models import Kazamata, Vilagkartya, Vezerkartya


class KazamataForm(forms.ModelForm):
    """Form a kazamata létrehozásához és szerkesztéséhez"""
    
    class Meta:
        model = Kazamata
        fields = ['nev', 'tipus']
        widgets = {
            'nev': forms.TextInput(attrs={
                'class': 'input-field',
                'placeholder': 'pl. A sötét kripta',
                'maxlength': 100
            }),
            'tipus': forms.Select(attrs={
                'class': 'input-field'
            }),
        }
        labels = {
            'nev': 'Kazamata neve',
            'tipus': 'Kazamata típusa'
        }


class VilagkartyaForm(forms.ModelForm):
    """Form a világkártya létrehozásához és szerkesztéséhez"""
    
    class Meta:
        model = Vilagkartya
        fields = ['nev', 'tipus', 'sebzes', 'eletero']
        widgets = {
            'nev': forms.TextInput(attrs={
                'class': 'input-field',
                'placeholder': 'pl. Tűz varázsló',
                'maxlength': 16
            }),
            'tipus': forms.Select(attrs={
                'class': 'input-field'
            }),
            'sebzes': forms.NumberInput(attrs={
                'class': 'input-field',
                'min': 2,
                'max': 100,
                'placeholder': '2-100'
            }),
            'eletero': forms.NumberInput(attrs={
                'class': 'input-field',
                'min': 1,
                'max': 100,
                'placeholder': '1-100'
            }),
        }
        labels = {
            'nev': 'Kártya neve',
            'tipus': 'Elem típusa',
            'sebzes': 'Sebzés',
            'eletero': 'Életerő'
        }


class VezerkartyaForm(forms.ModelForm):
    """Form a vezérkártya létrehozásához"""
    
    class Meta:
        model = Vezerkartya
        fields = ['eredeti_kartya', 'duplazas_tipusa']
        widgets = {
            'eredeti_kartya': forms.Select(attrs={
                'class': 'input-field',
                'onchange': 'updatePreview()'
            }),
            'duplazas_tipusa': forms.RadioSelect()
        }
        labels = {
            'eredeti_kartya': 'Alap kártya',
            'duplazas_tipusa': 'Mit duplázunk?'
        }

damareen/templates/damareen/master/create_kornyezet.html
{% extends 'damareen/base.html' %}

{% block title %}Új játékkörnyezet{% endblock %}

{% block content %}
<h2>➕ Új játékkörnyezet létrehozása</h2>

<div class="card">
    <h3>Alapadatok</h3>
    
    <form method="post">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="nev">Játékkörnyezet neve:</label>
            <input type="text" id="nev" name="nev" required 
                   placeholder="pl. Középfölde kalandjai">
        </div>
        
        <button type="submit" class="btn btn-success">
            ✅ Létrehozás
        </button>
        <a href="{% url 'damareen:master_dashboard' %}" class="btn btn-secondary">
            Mégse
        </a>
    </form>
</div>

<div class="card" style="margin-top: 30px;">
    <h3>ℹ️ További beállítások</h3>
    <p>A létrehozás után tudod beállítani:</p>
    <ul>
        <li>Kezdő gyűjtemény kártyáit</li>
        <li>Elérhető kazamatákat</li>
    </ul>
    <p style="color: #cbd5e0; margin-top: 10px; font-size: 14px;">
        <strong>💡 Tipp:</strong> A világkártyákat, vezéreket és kazamatákat a 
        <a href="{% url 'damareen:manage_vilagkartyak' %}" style="color: #daa520;">világkártya kezelő</a>, 
        <a href="{% url 'damareen:manage_vezerkartyak' %}" style="color: #daa520;">vezérkártya kezelő</a> és 
        <a href="{% url 'damareen:manage_kazamatak' %}" style="color: #daa520;">kazamata kezelő</a> 
        oldalakon kezelheted.
    </p>
</div>
{% endblock %}

damareen/templates/damareen/master/dashboard.html
{% extends 'damareen/base.html' %}

{% block title %}Játékmester műszerfal{% endblock %}

{% block content %}
<h2>🎲 Játékmester műszerfal</h2>

<div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; margin-bottom: 30px;">
    <div class="card" style="text-align: center; border-left-color: #daa520;">
        <h3>🃏 Világkártyák</h3>
        <p style="font-size: 32px; color: #daa520; font-weight: bold;">{{ vilag_kartyak.count }}</p>
        <a href="{% url 'damareen:manage_vilagkartyak' %}" class="btn">Kezelés</a>
    </div>
    
    <div class="card" style="text-align: center; border-left-color: #e74c3c;">
        <h3>👑 Vezérkártyák</h3>
        <p style="font-size: 32px; color: #e74c3c; font-weight: bold;">{{ vezer_kartyak.count }}</p>
        <a href="{% url 'damareen:manage_vezerkartyak' %}" class="btn">Kezelés</a>
    </div>
    
    <div class="card" style="text-align: center; border-left-color: #9b59b6;">
        <h3>🏰 Kazamaták</h3>
        <p style="font-size: 32px; color: #9b59b6; font-weight: bold;">{{ kazamatak.count }}</p>
        <a href="{% url 'damareen:manage_kazamatak' %}" class="btn">Kezelés</a>
    </div>
</div>

<div class="card">
    <h3>🌍 Játékkörnyezetek</h3>
    
    <div style="margin-bottom: 20px;">
        <a href="{% url 'damareen:create_kornyezet' %}" class="btn btn-success">
            ➕ Új játékkörnyezet
        </a>
    </div>
    
    {% if kornyezetek %}
        <table>
            <thead>
                <tr>
                    <th>Név</th>
                    <th>Létrehozva</th>
                    <th>Műveletek</th>
                </tr>
            </thead>
            <tbody>
                {% for kornyezet in kornyezetek %}
                <tr>
                    <td><strong>{{ kornyezet.nev }}</strong></td>
                    <td>{{ kornyezet.letrehozva|date:"Y.m.d H:i" }}</td>
                    <td>
                        <a href="{% url 'damareen:view_kornyezet' kornyezet.id %}" class="btn">
                            Szerkesztés
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p style="padding: 20px; text-align: center; color: #666;">
            Még nincs játékkörnyezeted. Hozz létre egyet!
        </p>
    {% endif %}
</div>

<div class="card" style="margin-top: 30px;">
    <h3>💡 Gyors linkek</h3>
    <div style="display: flex; gap: 15px; flex-wrap: wrap; margin-top: 15px;">
        <a href="{% url 'damareen:create_vilagkartya' %}" class="btn">➕ Új világkártya</a>
        <a href="{% url 'damareen:create_vezerkartya' %}" class="btn">➕ Új vezérkártya</a>
        <a href="{% url 'damareen:create_kazamata' %}" class="btn">➕ Új kazamata</a>
    </div>
</div>

<div class="card" style="margin-top: 30px;">
    <h3>📖 Útmutató</h3>
    <ol style="line-height: 2; color: #cbd5e0;">
        <li><strong>Hozz létre világkártyákat</strong> - Ezek lesznek az alapvető kártyák a játékban</li>
        <li><strong>Származtass vezérkártyákat</strong> - Erősebb verziók a világkártyákból</li>
        <li><strong>Állíts össze kazamatákat</strong> - Kihívások a játékosok számára</li>
        <li><strong>Készíts játékkörnyezetet</strong> - Válaszd ki a kezdő gyűjtemény kártyáit</li>
        <li><strong>Játékosok indíthatják a játékot!</strong> - A környezet készen áll</li>
    </ol>
</div>
{% endblock %}

damareen/templates/damareen/master/delete_vilagkartya.html
{% extends 'damareen/base.html' %}

{% block title %}Kártya törlése{% endblock %}

{% block content %}
<h2>🗑️ Világkártya törlése</h2>

<div class="card" style="border-left-color: #e74c3c;">
    <h3 style="color: #ff6b6b;">⚠️ Biztosan törölni szeretnéd?</h3>
    
    <div class="kartya kartya-{{ kartya.tipus }}" style="max-width: 300px; margin: 30px auto;">
        <h3>{{ kartya.nev }}</h3>
        <div class="kartya-stat">
            <span>⚔️ Sebzés:</span>
            <span style="color: #daa520;">{{ kartya.sebzes }}</span>
        </div>
        <div class="kartya-stat">
            <span>❤️ Életerő:</span>
            <span style="color: #e74c3c;">{{ kartya.eletero }}</span>
        </div>
        <div style="margin-top: 10px; text-align: center;">
            <span class="elem-icon elem-{{ kartya.tipus }}">
                {{ kartya.get_tipus_display }}
            </span>
        </div>
    </div>
    
    <p style="color: #ff6b6b; text-align: center; font-size: 18px; margin: 20px 0;">
        Ez a művelet nem visszavonható! A kártyát használó összes vezér, kazamata és játék is törlődni fog!
    </p>
    
    <form method="post" style="text-align: center;">
        {% csrf_token %}
        
        <button type="submit" class="btn btn-danger">
            ✅ Igen, törlöm
        </button>
        <a href="{% url 'damareen:manage_vilagkartyak' %}" class="btn btn-secondary">
            Mégse
        </a>
    </form>
</div>
{% endblock %}

damareen/templates/damareen/master/manage_vezerkartyak.html
{% extends 'damareen/base.html' %}

{% block title %}Vezérkártyák kezelése{% endblock %}

{% block content %}
<h2>👑 Vezérkártyák kezelése</h2>

<div style="margin-bottom: 30px;">
    <a href="{% url 'damareen:create_vezerkartya' %}" class="btn btn-success">
        ➕ Új vezérkártya létrehozása
    </a>
    <a href="{% url 'damareen:master_dashboard' %}" class="btn btn-secondary">
        ← Vissza a műszerfalhoz
    </a>
</div>

{% if kartyak %}
    <div class="grid">
        {% for kartya in kartyak %}
        <div class="card">
            <div class="kartya kartya-{{ kartya.tipus }}" style="border-width: 4px;">
                <div style="text-align: center; margin-bottom: 10px;">
                    <span style="background: linear-gradient(135deg, #daa520 0%, #ffd700 100%); color: #1a1a2e; padding: 4px 12px; border-radius: 15px; font-size: 12px; font-weight: bold;">
                        👑 VEZÉR
                    </span>
                </div>
                <h3>{{ kartya.nev }}</h3>
                <p style="font-size: 14px; color: #cbd5e0; text-align: center; margin-bottom: 10px;">
                    Származik: {{ kartya.eredeti_kartya.nev }}
                </p>
                <div class="kartya-stat">
                    <span>⚔️ Sebzés:</span>
                    <span style="color: #daa520;">{{ kartya.sebzes }}</span>
                </div>
                <div class="kartya-stat">
                    <span>❤️ Életerő:</span>
                    <span style="color: #e74c3c;">{{ kartya.eletero }}</span>
                </div>
                <div style="margin-top: 10px; text-align: center;">
                    <span class="elem-icon elem-{{ kartya.tipus }}">
                        {{ kartya.get_tipus_display }}
                    </span>
                </div>
                <p style="margin-top: 10px; text-align: center; font-size: 13px; color: #daa520;">
                    {{ kartya.get_duplazas_tipusa_display }}
                </p>
            </div>
            
            <div style="margin-top: 15px; display: flex; gap: 10px; justify-content: center;">
                <a href="{% url 'damareen:delete_vezerkartya' kartya.id %}" class="btn btn-danger">
                    🗑️ Törlés
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
{% else %}
    <div class="card" style="text-align: center; padding: 40px;">
        <p style="font-size: 18px; color: #cbd5e0;">
            Még nincsenek vezérkártyák. Hozz létre egyet!
        </p>
        <div style="margin-top: 20px;">
            <a href="{% url 'damareen:create_vezerkartya' %}" class="btn btn-success">
                ➕ Első vezérkártya létrehozása
            </a>
        </div>
    </div>
{% endif %}
{% endblock %}

damareen/templates/damareen/master/manage_vilagkartyak.html
{% extends 'damareen/base.html' %}

{% block title %}Világkártyák kezelése{% endblock %}

{% block content %}
<h2>🃏 Világkártyák kezelése</h2>

<div style="margin-bottom: 30px;">
    <a href="{% url 'damareen:create_vilagkartya' %}" class="btn btn-success">
        ➕ Új világkártya létrehozása
    </a>
    <a href="{% url 'damareen:master_dashboard' %}" class="btn btn-secondary">
        ← Vissza a műszerfalhoz
    </a>
</div>

{% if kartyak %}
    <div class="grid">
        {% for kartya in kartyak %}
        <div class="card">
            <div class="kartya kartya-{{ kartya.tipus }}">
                <h3>{{ kartya.nev }}</h3>
                <div class="kartya-stat">
                    <span>⚔️ Sebzés:</span>
                    <span style="color: #daa520;">{{ kartya.sebzes }}</span>
                </div>
                <div class="kartya-stat">
                    <span>❤️ Életerő:</span>
                    <span style="color: #e74c3c;">{{ kartya.eletero }}</span>
                </div>
                <div style="margin-top: 10px; text-align: center;">
                    <span class="elem-icon elem-{{ kartya.tipus }}">
                        {{ kartya.get_tipus_display }}
                    </span>
                </div>
            </div>
            
            <div style="margin-top: 15px; display: flex; gap: 10px; justify-content: center;">
                <a href="{% url 'damareen:edit_vilagkartya' kartya.id %}" class="btn">
                    ✏️ Szerkesztés
                </a>
                <a href="{% url 'damareen:delete_vilagkartya' kartya.id %}" class="btn btn-danger">
                    🗑️ Törlés
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
{% else %}
    <div class="card" style="text-align: center; padding: 40px;">
        <p style="font-size: 18px; color: #cbd5e0;">
            Még nincsenek világkártyák. Hozz létre egyet!
        </p>
        <div style="margin-top: 20px;">
            <a href="{% url 'damareen:create_vilagkartya' %}" class="btn btn-success">
                ➕ Első világkártya létrehozása
            </a>
        </div>
    </div>
{% endif %}
{% endblock %}