damareen/urls.py
"""
Damareen URL Configuration
"""
from django.urls import path
from . import views

app_name = 'damareen'

urlpatterns = [
    # Főoldal
    path('', views.index, name='index'),
    
    # Játékmester nézetek
    path('master/', views.master_dashboard, name='master_dashboard'),
    path('master/kornyezet/create/', views.create_kornyezet, name='create_kornyezet'),
    path('master/kornyezet/<int:kornyezet_id>/', views.view_kornyezet, name='view_kornyezet'),
    
    # Világkártyák kezelése
    path('master/vilagkartyak/', views.manage_vilagkartyak, name='manage_vilagkartyak'),
    path('master/vilagkartyak/create/', views.create_vilagkartya, name='create_vilagkartya'),
    path('master/vilagkartyak/<int:kartya_id>/edit/', views.edit_vilagkartya, name='edit_vilagkartya'),
    path('master/vilagkartyak/<int:kartya_id>/delete/', views.delete_vilagkartya, name='delete_vilagkartya'),
    
    # Vezérkártyák kezelése
    path('master/vezerkartyak/', views.manage_vezerkartyak, name='manage_vezerkartyak'),
    path('master/vezerkartyak/create/', views.create_vezerkartya, name='create_vezerkartya'),
    path('master/vezerkartyak/<int:kartya_id>/delete/', views.delete_vezerkartya, name='delete_vezerkartya'),
    
    # Kazamaták kezelése
    path('master/kazamatak/', views.manage_kazamatak, name='manage_kazamatak'),
    path('master/kazamatak/create/', views.create_kazamata, name='create_kazamata'),
    path('master/kazamatak/<int:kazamata_id>/edit/', views.edit_kazamata, name='edit_kazamata'),
    path('master/kazamatak/<int:kazamata_id>/delete/', views.delete_kazamata, name='delete_kazamata'),
    
    # Játékos nézetek
    path('player/', views.player_dashboard, name='player_dashboard'),
    path('player/jatek/start/<int:kornyezet_id>/', views.start_game, name='start_game'),
    path('player/jatek/<int:jatek_id>/', views.game_view, name='game_view'),
    path('player/jatek/<int:jatek_id>/pakli/', views.pakli_osszeallit, name='pakli_osszeallit'),
    path('player/jatek/<int:jatek_id>/harc/<int:kazamata_id>/', views.harc_indit, name='harc_indit'),
    path('player/game/<int:jatek_id>/battle/<int:kazamata_id>/', views.battle_arena, name='battle_arena'),
    path('player/jatek/<int:jatek_id>/harc/<int:harc_id>/eredmeny/', views.harc_eredmeny, name='harc_eredmeny'),
    path('player/game/<int:jatek_id>/harc/<int:harc_id>/jutalom/', views.jutalom_valaszt, name='jutalom_valaszt'),
    
    # Autentikáció
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    
    # Rangsor és achievementek
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('achievements/', views.my_achievements, name='achievements'),
]

dusza25/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('damareen.urls')),
]

damareen/forms.py
from django import forms
from .models import Kazamata, Vilagkartya, Vezerkartya


class KazamataForm(forms.ModelForm):
    """Form a kazamata létrehozásához és szerkesztéséhez"""
    
    class Meta:
        model = Kazamata
        fields = ['nev', 'tipus']
        widgets = {
            'nev': forms.TextInput(attrs={
                'class': 'input-field',
                'placeholder': 'pl. A sötét kripta',
                'maxlength': 100
            }),
            'tipus': forms.Select(attrs={
                'class': 'input-field'
            }),
        }
        labels = {
            'nev': 'Kazamata neve',
            'tipus': 'Kazamata típusa'
        }


class VilagkartyaForm(forms.ModelForm):
    """Form a világkártya létrehozásához és szerkesztéséhez"""
    
    class Meta:
        model = Vilagkartya
        fields = ['nev', 'tipus', 'sebzes', 'eletero']
        widgets = {
            'nev': forms.TextInput(attrs={
                'class': 'input-field',
                'placeholder': 'pl. Tűz varázsló',
                'maxlength': 16
            }),
            'tipus': forms.Select(attrs={
                'class': 'input-field'
            }),
            'sebzes': forms.NumberInput(attrs={
                'class': 'input-field',
                'min': 2,
                'max': 100,
                'placeholder': '2-100'
            }),
            'eletero': forms.NumberInput(attrs={
                'class': 'input-field',
                'min': 1,
                'max': 100,
                'placeholder': '1-100'
            }),
        }
        labels = {
            'nev': 'Kártya neve',
            'tipus': 'Elem típusa',
            'sebzes': 'Sebzés',
            'eletero': 'Életerő'
        }


class VezerkartyaForm(forms.ModelForm):
    """Form a vezérkártya létrehozásához"""
    
    class Meta:
        model = Vezerkartya
        fields = ['eredeti_kartya', 'duplazas_tipusa']
        widgets = {
            'eredeti_kartya': forms.Select(attrs={
                'class': 'input-field',
                'onchange': 'updatePreview()'
            }),
            'duplazas_tipusa': forms.RadioSelect()
        }
        labels = {
            'eredeti_kartya': 'Alap kártya',
            'duplazas_tipusa': 'Mit duplázunk?'
        }

damareen/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.db import transaction
from django.db.models import Max

from .models import (
    UserProfile, JatekKornyezet, Jatek, Jatekoskartya,
    Pakli, PakliKartya, Kazamata, Harc, Vilagkartya,
    Vezerkartya, GyujtemenyKartya, KazamataKartya,
    Achievement, PlayerAchievement,
    ELEMENT_FIRE, ELEMENT_EARTH, ELEMENT_WATER, ELEMENT_AIR
)
from .game_logic import harc_vegrehajtasa, jutalom_alkalmazasa, frissit_rangsort
from .forms import KazamataForm, VilagkartyaForm, VezerkartyaForm


def index(request):
    """Főoldal"""
    return render(request, 'damareen/index.html')


def user_login(request):
    """Bejelentkezés"""
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            messages.success(request, f'Üdvözöl a Damareen, {user.username}!')
            return redirect('damareen:index')
        else:
            messages.error(request, 'Hibás felhasználónév vagy jelszó!')
    
    return render(request, 'damareen/login.html')


def user_logout(request):
    """Kijelentkezés"""
    logout(request)
    messages.info(request, 'Sikeresen kijelentkeztél!')
    return redirect('damareen:index')


def user_register(request):
    """Regisztráció"""
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')
        user_type = request.POST.get('user_type', UserProfile.PERMISSION_PLAYER)
        
        if password != password2:
            messages.error(request, 'A jelszavak nem egyeznek!')
        elif User.objects.filter(username=username).exists():
            messages.error(request, 'Ez a felhasználónév már foglalt!')
        else:
            user = User.objects.create_user(username=username, password=password)
            UserProfile.objects.create(user=user, user_type=user_type)
            messages.success(request, 'Sikeres regisztráció! Most már bejelentkezhetsz.')
            return redirect('damareen:login')
    
    return render(request, 'damareen/register.html')


@login_required
def master_dashboard(request):
    """Játékmester műszerfal"""
    kornyezetek = JatekKornyezet.objects.filter(keszitette=request.user)
    vilag_kartyak = Vilagkartya.objects.all()
    vezer_kartyak = Vezerkartya.objects.all()
    kazamatak = Kazamata.objects.all()
    
    return render(request, 'damareen/master/dashboard.html', {
        'kornyezetek': kornyezetek,
        'vilag_kartyak': vilag_kartyak,
        'vezer_kartyak': vezer_kartyak,
        'kazamatak': kazamatak,
    })


@login_required
def create_kornyezet(request):
    """Új játékkörnyezet létrehozása"""
    if request.method == 'POST':
        nev = request.POST.get('nev')
        
        # Játékkörnyezet létrehozása
        kornyezet = JatekKornyezet.objects.create(
            nev=nev,
            keszitette=request.user
        )
        
        messages.success(request, f'Játékkörnyezet "{nev}" létrehozva!')
        return redirect('damareen:view_kornyezet', kornyezet_id=kornyezet.id)
    
    vilag_kartyak = Vilagkartya.objects.all()
    return render(request, 'damareen/master/create_kornyezet.html', {
        'vilag_kartyak': vilag_kartyak
    })


@login_required
def view_kornyezet(request, kornyezet_id):
    """Játékkörnyezet megtekintése"""
    kornyezet = get_object_or_404(JatekKornyezet, id=kornyezet_id, keszitette=request.user)
    
    if request.method == 'POST':
        # Kezdő gyűjtemény frissítése
        valasztott_kartyak = request.POST.getlist('kartyak')
        GyujtemenyKartya.objects.filter(kornyezet=kornyezet).delete()
        
        for kartya_id in valasztott_kartyak:
            GyujtemenyKartya.objects.create(
                kornyezet=kornyezet,
                kartya_id=kartya_id
            )
        
        messages.success(request, 'Kezdő gyűjtemény frissítve!')
    
    vilag_kartyak = Vilagkartya.objects.all()
    kezdo_gyujtemeny = kornyezet.kezdo_gyujtemeny.all()
    kazamatak = Kazamata.objects.all()
    
    return render(request, 'damareen/master/view_kornyezet.html', {
        'kornyezet': kornyezet,
        'vilag_kartyak': vilag_kartyak,
        'kezdo_gyujtemeny': kezdo_gyujtemeny,
        'kazamatak': kazamatak
    })


@login_required
def player_dashboard(request):
    """Játékos műszerfal"""
    jatekok = Jatek.objects.filter(jatekos=request.user)
    kornyezetek = JatekKornyezet.objects.all()
    
    return render(request, 'damareen/player/dashboard.html', {
        'jatekok': jatekok,
        'kornyezetek': kornyezetek
    })


@login_required
@transaction.atomic
def start_game(request, kornyezet_id):
    """Új játék indítása"""
    kornyezet = get_object_or_404(JatekKornyezet, id=kornyezet_id)
    
    # Ellenőrizzük, hogy van-e már játék ezzel a környezettel
    jatek, created = Jatek.objects.get_or_create(
        jatekos=request.user,
        kornyezet=kornyezet
    )
    
    if created:
        # Kezdő gyűjtemény másolása
        for gyujtemeny_kartya in kornyezet.kezdo_gyujtemeny.all():
            Jatekoskartya.objects.create(
                jatek=jatek,
                eredeti_kartya=gyujtemeny_kartya.kartya,
                aktualis_sebzes=gyujtemeny_kartya.kartya.sebzes,
                aktualis_eletero=gyujtemeny_kartya.kartya.eletero
            )
        messages.success(request, f'Új játék indítva: {kornyezet.nev}')
    else:
        messages.info(request, 'Folytatod a megkezdett játékot.')
    
    return redirect('damareen:game_view', jatek_id=jatek.id)


@login_required
def game_view(request, jatek_id):
    """Játék nézet"""
    jatek = get_object_or_404(Jatek, id=jatek_id, jatekos=request.user)
    gyujtemeny = jatek.gyujtemeny.all()
    pakli = None
    
    try:
        pakli = jatek.pakli
    except Pakli.DoesNotExist:
        pass
    
    kazamatak = Kazamata.objects.all()
    utolso_harcok = jatek.harcok.filter(befejezve=True).order_by('-inditas')[:5]
    
    return render(request, 'damareen/player/game_view.html', {
        'jatek': jatek,
        'gyujtemeny': gyujtemeny,
        'pakli': pakli,
        'kazamatak': kazamatak,
        'utolso_harcok': utolso_harcok
    })


@login_required
@transaction.atomic
def pakli_osszeallit(request, jatek_id):
    """Pakli összeállítása"""
    jatek = get_object_or_404(Jatek, id=jatek_id, jatekos=request.user)
    
    if request.method == 'POST':
        valasztott_kartyak = request.POST.getlist('kartyak')
        
        if not valasztott_kartyak:
            messages.error(request, 'Válassz ki legalább egy kártyát!')
            return redirect('damareen:pakli_osszeallit', jatek_id=jatek_id)
        
        # Régi pakli törlése
        try:
            jatek.pakli.delete()
        except Pakli.DoesNotExist:
            pass
        
        # Új pakli létrehozása
        pakli = Pakli.objects.create(jatek=jatek)
        
        for i, kartya_id in enumerate(valasztott_kartyak):
            PakliKartya.objects.create(
                pakli=pakli,
                kartya_id=kartya_id,
                sorrend=i + 1
            )
        
        messages.success(request, f'Pakli összeállítva {len(valasztott_kartyak)} kártyával!')
        return redirect('damareen:game_view', jatek_id=jatek_id)
    
    gyujtemeny = jatek.gyujtemeny.all()
    return render(request, 'damareen/player/pakli_osszeallit.html', {
        'jatek': jatek,
        'gyujtemeny': gyujtemeny
    })


@login_required
@transaction.atomic
def harc_indit(request, jatek_id, kazamata_id):
    """Harc indítása - új: WebSocket alapú real-time battle"""
    jatek = get_object_or_404(Jatek, id=jatek_id, jatekos=request.user)
    kazamata = get_object_or_404(Kazamata, id=kazamata_id)
    
    # Ellenőrizzük, hogy van-e pakli
    try:
        pakli = jatek.pakli
    except Pakli.DoesNotExist:
        messages.error(request, '❌ Először állíts össze egy paklit!')
        return redirect('damareen:game_view', jatek_id=jatek_id)
    
    # Ellenőrizzük a kártyák számát
    pakli_meret = pakli.get_kartyak_szama()
    kazamata_meret = kazamata.get_kartyak_szama()
    
    if pakli_meret != kazamata_meret:
        messages.error(request, 
            f'❌ A paklidban {pakli_meret} kártya van, de a kazamatához {kazamata_meret} kell!')
        return redirect('damareen:game_view', jatek_id=jatek_id)
    
    # Redirect to WebSocket battle arena
    return redirect('damareen:battle_arena', jatek_id=jatek_id, kazamata_id=kazamata_id)


@login_required
def battle_arena(request, jatek_id, kazamata_id):
    """Real-time battle arena with WebSocket"""
    jatek = get_object_or_404(Jatek, id=jatek_id, jatekos=request.user)
    kazamata = get_object_or_404(Kazamata, id=kazamata_id)
    
    return render(request, 'damareen/player/battle_arena.html', {
        'jatek': jatek,
        'kazamata': kazamata
    })


@login_required
def harc_eredmeny(request, jatek_id, harc_id):
    """Harc eredményének megtekintése"""
    jatek = get_object_or_404(Jatek, id=jatek_id, jatekos=request.user)
    harc = get_object_or_404(Harc, id=harc_id, jatek=jatek)
    
    # Rangsor frissítése (csak egyszer)
    if harc.befejezve and not harc.rangsor_frissitve:
        frissit_rangsort(request.user, harc.jatekos_gyozott)

damareen/templates/damareen/index.html
{% extends 'damareen/base.html' %}

{% block extra_css %}
<style>
    .hero-section {
        text-align: center;
        padding: 60px 20px;
        background: linear-gradient(135deg, rgba(139, 69, 19, 0.2) 0%, rgba(101, 67, 33, 0.3) 100%);
        border-radius: 15px;
        border: 2px solid rgba(218, 165, 32, 0.3);
        margin-bottom: 40px;
        box-shadow: 0 10px 40px rgba(0,0,0,0.4);
    }
    
    .hero-title {
        font-family: 'Cinzel', serif;
        font-size: 4em;
        color: #daa520;
        text-shadow: 
            0 0 20px rgba(218, 165, 32, 0.8),
            0 0 40px rgba(218, 165, 32, 0.5),
            3px 3px 6px rgba(0,0,0,0.8);
        margin-bottom: 20px;
        letter-spacing: 6px;
    }
    
    .hero-subtitle {
        font-size: 24px;
        color: #cbd5e0;
        font-style: italic;
        margin-bottom: 40px;
    }
    
    .feature-grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
        gap: 30px;
        margin: 40px 0;
    }
    
    .feature-card {
        background: linear-gradient(135deg, rgba(60, 60, 80, 0.5) 0%, rgba(40, 40, 60, 0.5) 100%);
        padding: 30px;
        border-radius: 12px;
        border: 2px solid rgba(218, 165, 32, 0.3);
        transition: all 0.3s;
        box-shadow: 0 4px 12px rgba(0,0,0,0.3);
    }
    
    .feature-card:hover {
        transform: translateY(-5px);
        border-color: #daa520;
        box-shadow: 0 8px 24px rgba(218, 165, 32, 0.3);
    }
    
    .feature-icon {
        font-size: 48px;
        margin-bottom: 15px;
    }
    
    .rules-box {
        background: linear-gradient(135deg, rgba(30, 30, 50, 0.6) 0%, rgba(20, 20, 40, 0.6) 100%);
        padding: 40px;
        border-radius: 15px;
        border: 2px solid rgba(218, 165, 32, 0.4);
        margin-top: 40px;
    }
    
    .rules-box ul {
        list-style: none;
        padding-left: 0;
    }
    
    .rules-box li {
        padding: 12px 0;
        border-bottom: 1px solid rgba(218, 165, 32, 0.2);
        font-size: 18px;
    }
    
    .rules-box li:last-child {
        border-bottom: none;
    }
    
    .cta-buttons {
        margin-top: 40px;
        text-align: center;
    }
    
    .cta-buttons .btn {
        margin: 10px;
        font-size: 18px;
        padding: 16px 32px;
    }
    
    /* ============================================
       MOBILE RESPONSIVE STYLES
       ============================================ */
    
    /* Mobile devices (max-width: 768px) */
    @media screen and (max-width: 768px) {
        .hero-section {
            padding: 40px 15px;
        }
        
        .hero-title {
            font-size: 2.5em;
            letter-spacing: 3px;
        }
        
        .hero-subtitle {
            font-size: 18px;
            margin-bottom: 30px;
        }
        
        .cta-buttons .btn {
            display: block;
            width: 100%;
            margin: 8px 0;
            font-size: 16px;
            padding: 14px 24px;
        }
        
        .feature-grid {
            grid-template-columns: 1fr;
            gap: 20px;
        }
        
        .feature-card {
            padding: 25px;
        }
        
        .feature-icon {
            font-size: 40px;
        }
        
        .rules-box {
            padding: 25px 15px;
        }
        
        .rules-box li {
            font-size: 15px;
            padding: 10px 0;
        }
        
        .rules-box h3 {
            font-size: 1.6em;
            margin-bottom: 20px;
        }
    }
    
    /* Small mobile devices (max-width: 480px) */
    @media screen and (max-width: 480px) {
        .hero-section {
            padding: 30px 10px;
        }
        
        .hero-title {
            font-size: 2em;
            letter-spacing: 2px;
        }
        
        .hero-subtitle {
            font-size: 16px;
            margin-bottom: 25px;
        }
        
        .cta-buttons .btn {
            font-size: 15px;
            padding: 12px 20px;
        }
        
        .feature-card {
            padding: 20px;
        }
        
        .feature-card h3 {
            font-size: 1.3em;
        }
        
        .feature-icon {
            font-size: 36px;
        }
        
        .rules-box {
            padding: 20px 12px;
        }
        
        .rules-box li {
            font-size: 14px;
            padding: 8px 0;
        }
        
        .rules-box h3 {
            font-size: 1.4em;
        }
        
        .elem-icon {
            font-size: 9px;
            padding: 3px 6px;
        }
    }
</style>
{% endblock %}

{% block content %}
<div class="hero-section">
    <h1 class="hero-title">DAMAREEN</h1>
    <p class="hero-subtitle">A gyűjtögetős fantasy kártyajáték</p>
    
    <div class="cta-buttons">
        {% if user.is_authenticated %}
            <a href="{% url 'damareen:player_dashboard' %}" class="btn btn-success">
                🎮 Játék indítása
            </a>
            <a href="{% url 'damareen:master_dashboard' %}" class="btn">
                🎲 Játékmester mód
            </a>
        {% else %}
            <a href="{% url 'damareen:login' %}" class="btn btn-success">
                🔑 Bejelentkezés
            </a>
            <a href="{% url 'damareen:register' %}" class="btn">
                📝 Regisztráció
            </a>
        {% endif %}
    </div>
</div>

<div style="margin: 40px auto; max-width: 1000px;">
    <div style="text-align: center; margin-bottom: 40px;">
        <h2 style="font-size: 2.5em;">Üdvözlünk a Damareen világában!</h2>
        <p style="font-size: 20px; line-height: 1.8; margin-top: 20px;">
            Stratégia, szerencse és képzelet találkozása. Fejleszd kártyáidat, 
            küzdj meg kazamatákban, és váljél legendává!
        </p>
    </div>
    
    <div class="feature-grid">
        <div class="feature-card">
            <div class="feature-icon">🎮</div>
            <h3>Játékosként</h3>
            <p style="line-height: 1.8;">
                Válassz egy játékkörnyezetet, állítsd össze a paklidat, és indulj harcba 
                a kazamaták ellen! Minden győzelemért jutalmat kapsz, amivel tovább 
                fejlesztheted kártyáidat.
            </p>
        </div>
        
        <div class="feature-card">
            <div class="feature-icon">🎲</div>
            <h3>Játékmesterként</h3>
            <p style="line-height: 1.8;">
                Hozz létre saját világokat! Definiálj világkártyákat, vezéreket és 
                kazamatákat. Állítsd össze a kezdő gyűjteményt, és engedd játszani 
                a játékosokat!
            </p>
        </div>
    </div>
</div>

<div class="rules-box">
    <h3 style="text-align: center; font-size: 2em; margin-bottom: 30px;">
        ⚔️ Játék szabályok
    </h3>
    <ul>
        <li>
            🃏 Minden kártyának van <strong style="color: #daa520;">sebzés</strong>, 
            <strong style="color: #daa520;">életerő</strong> és 
            <strong style="color: #daa520;">típus</strong> értéke
        </li>
        <li>
            ⚔️ Kártyák ütközete: Sebzés vs Életerő, majd típus előny dönt
        </li>
        <li>
            <span style="display: inline-flex; gap: 10px; align-items: center;">
                🔥 Típus előnyök: 
                <span class="elem-icon elem-tuz" style="font-size: 11px; padding: 4px 8px;">TŰZ</span> → 
                <span class="elem-icon elem-fold" style="font-size: 11px; padding: 4px 8px;">FÖLD</span> → 
                <span class="elem-icon elem-viz" style="font-size: 11px; padding: 4px 8px;">VÍZ</span> → 
                <span class="elem-icon elem-levego" style="font-size: 11px; padding: 4px 8px;">LEVEGŐ</span> → 
                <span class="elem-icon elem-tuz" style="font-size: 11px; padding: 4px 8px;">TŰZ</span>
            </span>
        </li>
        <li>
            🏆 Legalább annyi győzelemmel kell rendelkezned, amennyi a kazamata kártyáinak száma
        </li>
        <li>
            💎 Győzelem esetén fejlesztheted egyik kártyádat
        </li>
        <li>
            📈 Kazamata típusok: 
            <strong style="color: #90ee90;">Egyszerű (+1 sebzés)</strong>, 
            <strong style="color: #64b5f6;">Kis (+2 életerő)</strong>, 
            <strong style="color: #daa520;">Nagy (+3 sebzés)</strong>
        </li>
    </ul>
</div>

<div style="margin-top: 60px; text-align: center; padding: 40px; background: linear-gradient(135deg, rgba(139, 69, 19, 0.2) 0%, rgba(101, 67, 33, 0.2) 100%); border-radius: 15px; border: 2px solid rgba(218, 165, 32, 0.3);">
    <h3 style="font-size: 2em; margin-bottom: 20px;">Készen állsz a kalandra?</h3>
    <p style="font-size: 18px; margin-bottom: 30px;">
        Lépj be a Damareen világába és szerezd meg az uralmat a kártyák felett!
    </p>
    
    {% if not user.is_authenticated %}
        <a href="{% url 'damareen:register' %}" class="btn btn-success" style="font-size: 20px; padding: 18px 36px;">
            ⚔️ Csatlakozz most!
        </a>
    {% endif %}
</div>
{% endblock %}

damareen/templates/damareen/login.html
{% extends 'damareen/base.html' %}

{% block title %}Bejelentkezés - Damareen{% endblock %}

{% block content %}
<div style="max-width: 500px; margin: 0 auto;">
    <h2>🔑 Bejelentkezés</h2>
    
    <form method="post" style="margin-top: 30px;">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="username">Felhasználónév:</label>
            <input type="text" id="username" name="username" required>
        </div>
        
        <div class="form-group">
            <label for="password">Jelszó:</label>
            <input type="password" id="password" name="password" required>
        </div>
        
        <button type="submit" class="btn btn-success">Bejelentkezés</button>
        <a href="{% url 'damareen:register' %}" class="btn btn-secondary" style="margin-left: 10px;">
            Regisztráció
        </a>
    </form>
</div>
{% endblock %}

damareen/templates/damareen/register.html
{% extends 'damareen/base.html' %}

{% block title %}Regisztráció - Damareen{% endblock %}

{% block content %}
<div style="max-width: 500px; margin: 0 auto;">
    <h2>📝 Regisztráció</h2>
    
    <form method="post" style="margin-top: 30px;">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="username">Felhasználónév:</label>
            <input type="text" id="username" name="username" required>
        </div>
        
        <div class="form-group">
            <label for="password">Jelszó:</label>
            <input type="password" id="password" name="password" required>
        </div>
        
        <div class="form-group">
            <label for="password2">Jelszó megerősítése:</label>
            <input type="password" id="password2" name="password2" required>
        </div>
        
        <div class="form-group">
            <label for="user_type">Szerepkör:</label>
            <select id="user_type" name="user_type">
                <option value="player">Játékos</option>
                <option value="master">Játékmester</option>
            </select>
        </div>
        
        <button type="submit" class="btn btn-success">Regisztráció</button>
        <a href="{% url 'damareen:login' %}" class="btn btn-secondary" style="margin-left: 10px;">
            Bejelentkezés
        </a>
    </form>
</div>
{% endblock %}